on: 
  push:
    branches:
      - "master"
name: 🚀 Deploy portfolio on push

jobs:
  client-deploy:
    name: Deploy portfolio to Cpanel
    runs-on: ubuntu-latest
    steps:
    - name: Get latest client code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - name: Build project
      run: |
        npm install
        npm run build

    - name: Copy .htaccess file
      run: cp .htaccess build/

    - name: List output files
      run: find build/ -print
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.ftp_server }}
        FTP_USERNAME: ${{ secrets.ftp_username }}
        FTP_PASSWORD: ${{ secrets.ftp_password }}
        PORT: ${{ secrets.ftp_port }}
        LOCAL_DIR: build/
        REMOTE_DIR: portfolio.hoanganhminh.blog/
        ARGS: --verbose
        METHOD: sftp
